### ISSUE TITLE
Лендинг ITGM №9

### ISSUE THREAD

**Issue by mike1pol** [Piter-United/index#59]
## Лендинг ITGM №9
- [x] #56 Изменение даты проведения мероприятия
- [x] #54 Правка цветовой схемы
- [x] #55 Актуализация программы мероприятия
- [x] #57 Актуализация списка сообществ участников
- [x] #58 Актуализация партнеров мероприятия
- [x] #43 Актуализация списка отзывов
- [x] #47 Правки по адаптивной верстки
- [ ] #37 Правки по интеграции со соц. сетями
- [ ] #60 Интеграция программы сообществ с Google spreadsheet
